[env:teensy41]
platform = platformio/teensy@^5.1.0
board = teensy41
framework = arduino
upload_protocol = custom
monitor_speed = 115200
extra_scripts =
  pre:scripts/patch_teensy_usb.py
  pre:scripts/generate_antenna_config.py
  scripts/teensy_upload.py
platform_packages =
  framework-arduinoteensy@>=1.160.0
build_flags =
  -D USB_AUDIO
  -D QUACKHEAD
  -D USB_DUAL_SERIAL_AUDIO
#lib_ldf_mode = deep+
lib_deps =
  fastled/FastLED @ 3.10.3

[env:quackhead_v4]
extends = env:teensy41
extra_scripts =
    pre:scripts/patch_teensy_usb.py
    pre:scripts/generate_antenna_config.py
upload_command =
    ./scripts/upload_quackhead.sh -firmware $SOURCE -user ${sysenv.SSH_HEAD_UPLOAD_USER}:duck -duckling ${sysenv.SSH_HEAD_UPLOAD_HOST}:bdx-head.local
